In [1]:
import numpy as np

In [3]:
stock_change = np.random.normal(0, 1, (4, 5))
stock_change

array([[-0.09526272,  2.12352125, -1.54715426,  0.03956923, -0.86139794],
       [ 0.13005267, -0.18765363, -0.04305824,  0.25260692, -0.06299184],
       [ 0.19126235, -1.05368953,  0.41536466,  0.49574321, -1.02353256],
       [ 0.13293816, -0.14233106,  0.62295846,  0.10491633, -0.39769164]])

In [6]:
stock_change[0, 0:3]

array([-0.09526272,  2.12352125, -1.54715426])

In [7]:
stock_change.reshape([5, 4])

array([[-0.09526272,  2.12352125, -1.54715426,  0.03956923],
       [-0.86139794,  0.13005267, -0.18765363, -0.04305824],
       [ 0.25260692, -0.06299184,  0.19126235, -1.05368953],
       [ 0.41536466,  0.49574321, -1.02353256,  0.13293816],
       [-0.14233106,  0.62295846,  0.10491633, -0.39769164]])

In [8]:
stock_change.resize([5, 4])

In [10]:
stock_change.shape

(5, 4)

In [11]:
stock_change.T

array([[-0.09526272, -0.86139794,  0.25260692,  0.41536466, -0.14233106],
       [ 2.12352125,  0.13005267, -0.06299184,  0.49574321,  0.62295846],
       [-1.54715426, -0.18765363,  0.19126235, -1.02353256,  0.10491633],
       [ 0.03956923, -0.04305824, -1.05368953,  0.13293816, -0.39769164]])

In [12]:
stock_change.astype(np.int32)

array([[ 0,  2, -1,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0, -1],
       [ 0,  0, -1,  0],
       [ 0,  0,  0,  0]], dtype=int32)

In [16]:
stock_change.tobytes

<function ndarray.tobytes>

In [18]:
stock_change.mean()

-0.045291508955172435

In [20]:
stock_change

array([[-0.00952627,  0.21235213, -0.15471543,  0.00395692],
       [-0.08613979,  0.01300527, -0.01876536, -0.00430582],
       [ 0.02526069, -0.00629918,  0.01912624, -0.10536895],
       [ 0.04153647,  0.04957432, -0.10235326,  0.01329382],
       [-0.01423311,  0.06229585,  0.01049163, -0.03976916]])